version: '2'

services:
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9941:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${MY_IP}
      KAFKA_ADVERTISED_PORT: 9941
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_CREATE_TOPICS: "com.games.test:5:1"
  postgres:
    image: postgres:9.5
    ports:
      - "8585:5432"
  statsd:
    image: hopsoft/graphite-statsd
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "40001:8125/udp"
      - "40002:8126"
  redis:
    image: redis
    ports:
      - "6333:6379"
  cassandra:
    image: cassandra:3.11.1
    ports:
      - "4042:9042"
