
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/DataDog/datadog-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/alexcesaro/statsd"
  version = "2.0.0"

[[constraint]]
  name = "github.com/bsm/redis-lock"
  version = "6.0.0"

[[constraint]]
  name = "github.com/confluentinc/confluent-kafka-go"
  version = "0.11.0"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.11.2"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.7.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.15.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "2.0.0"

[[constraint]]
  name = "github.com/jrallison/go-workers"
  revision = "dbf81d0b75bbe2fd90ef66a07643dd70cb42a88a"
